### ISSUE TITLE
could I get your result file of the SISSOR for the PGP1 cell 

### ISSUE THREAD

**Issue by NieRui0327** [pjedge/SISSOR#1]
HI, my name is Nie Rui.  I'm a master student from BIG , China. I want to know the fragment overlap of the 3 PGP1 cells. I know in the supplemental file where you have given a Summary of HMM SISSOR fragments from 3 PGP1 fibroblast cells table. But it's not abundant. So could you give me the detail of your result?  Thanks very much.

**Comment by pjedge** [comment]
Hi Nie.

Sorry for the late reply. I'm glad you're interested in the paper. The final result file for the strand-pairing analysis is an extremely large set of tables with information for each chamber for each genomic position.

If you'd like, I can compress the calls that were used to compare strands for the final result down to a set of 72 GFF files (that would represent spans of reference calls as intervals), and this should be sufficiently small to easily share. Would this be sufficient for your purposes?

**Comment by NieRui0327** [comment]
Hi Edge,
  It's very exciting for me to receive your reply.  The 72 GFF files are sufficient for my purposes. Could you send it to my e-mail? The address is 892272536@qq.com. Thanks again.

**Comment by NieRui0327** [comment]
Hi Peter，
    I'm sorry I write to you again. But I haven't got your email until now, I wonder if my address shielded it. So if you have sent the mail to me, please tell me here, or if it was the shield, please send it to nierui@big.ac.cn again. Thank you! Sorry for the inconvenience caused to you.

**Comment by NieRui0327** [comment]
Hi Peter，
I'm sorry I write to you again. But I haven't got your email until now, I wonder whether my address shielded it. So if you have sent the mail to me, please tell me here, or if it was the shield, please send it to nierui@big.ac.cn again. Thank you! Sorry for the inconvenience caused to you.

**Comment by pjedge** [comment]
Hi Nie,

Sorry I forgot to message you. I will try to send you the files as soon as I can, but I am very busy right now with my other schoolwork. In order to send you these files I'll first have to restore a data backup, write code to convert the tables into a GFF format, and then do some analysis to verify that there aren't issues with the converted data and the same information from the original analysis is preserved.

I figure that once I do these steps I'll probably put the files on this github repo (or at least link to them from here), so that anyone else who is curious can also look at them. At any rate, I'll update you here one I've done it.

Hopefully this isn't a large problem -- I apologize but I have a lot on my plate right now

**Comment by NieRui0327** [comment]
Hi Peter,
    It doesn't matter.  Thanks again! Wish you all the best!

**Comment by pjedge** [comment]
GFF files containing the SISSOR strand information used for the haplotype-based call validation are now linked from the README
